---
docs:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - docs/**
          # - docs_src/**
          - all-globs-to-all-files:
              - '!contextforge_cli/**'
              - '!pyproject.toml'
internal:
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**
              - scripts/**
              - .gitignore
              - .pre-commit-config.yaml
              # - pdm_build.py
              - requirements*.txt
          - all-globs-to-all-files:
              - '!docs/**'
              - '!contextforge_cli/**'
              - '!pyproject.toml'
